done with albums and songs fix the error on sql complete on desc
its because sql is default incasesensitive so i create col with name albumId wcich accessing it is hard so i just renamme it to col album_id and acces it with the same name but to return it to frontend i need to map or change the album_id to albumId

for the pg migrate erro this
'''
Error: Not run migration 1672023561185_create-table-albums is preceding already run migration 1671971445192_create-table-albums
'''

just delete column in pgmigrations table in db and rerun npm run migrate up